site_name: TypischerKater's Wiki
site_url: https://wiki.brunosolf.de/
site_author: Bruno Solf

# Repository
repo_name: typischerkater/mkdocs-wiki
repo_url: https://github.com/typischerkater/mkdocs-wiki

# Copyright
copyright: Copyright &copy; 2025 - 2025 Bruno Solf

theme:
  name: material
  icon:
    logo: logo
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

plugins:
  - search
  - tags:
      tags_file: tags.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TypischerKater/
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/typischerkater/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Proxmox:
    - Create a LXC Container on Proxmox: proxmox/create-a-lxc-container-on-proxmox.md
    - No Backup on unprivileged LXC container possible: proxmox/no-backup-on-unprivileged-lxc-container-possible.md
    - Passthrough HDD to LXC container Proxmox: proxmox/passthrough-hdd-to-lxc-container-proxmox.md
    - Add Proxmox Backup to store the LXC Backups on a NAS: proxmox/add-proxmox-backup-to-store-the-lxc-backups-on-a-nas.md
    - Install Docker on an LXC Container: proxmox/install-docker-on-an-lxc-container.md
  - Computer:
    - Delete and remove the complete deleted files history list from for example recuva: computer/delete-and-remove-the-complete-deleted-files-history-list-from-for-example-recuva.md
    - HDD shows less space available that is actually used: computer/hdd-shows-less-space-available-that-is-actually-used.md
    - Format a Hard Drive & Delete Recovery Partitions: computer/format-a-hard-drive-_-delete-recovery-partitions.md
  - Home Server:
    - Update Portainer: home-server/update-portainer.md
  - Coding:
    - Update Angular dependencies all at once: coding/update-angular-dependencies-all-at-once.md
    - SQL Backup with Blobs can not be reimported: coding/sql-backup-with-blobs-can-not-be-reimported.md
  - Raspberry PI:
    - Setup Raspberry PI: raspberry-pi/setup-raspberry-pi.md
    - Setup Java on Raspberry PI: raspberry-pi/setup-java-on-raspberry-pi.md
  - Python:
    - Start Mkdocs Project: python/start-mkdocs-project.md
  - Tags: tags.md